import requests

url ='http://127.0.0.1:8000/celulares'

# Lista completa dos dicionários de celulares (sem os campos "id")

celulares = [
    {
        "marca": "Samsung",
        "modelo": "Galaxy A54",
        "versao": "Galaxy A54 V3",
        "so": "Android 13",
        "interface": "One UI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Samsung",
        "modelo": "Galaxy M14",
        "versao": "Galaxy M14 V4",
        "so": "Android 13",
        "interface": "One UI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Samsung",
        "modelo": "Galaxy S21 FE",
        "versao": "Galaxy S21 FE V5"
        , "so": "Android 13",
        "interface": "One UI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Samsung",
        "modelo": "Galaxy A34",
        "versao": "Galaxy A34 V6",
        "so": "Android 13",
        "interface": "One UI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Samsung",
        "modelo": "Galaxy M54",
        "versao": "Galaxy M54 V7",
        "so": "Android 13",
        "interface": "One UI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Samsung",
        "modelo": "Galaxy S22",
        "versao": "Galaxy S22 V8",
        "so": "Android 13",
        "interface": "One UI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Samsung",
        "modelo": "Galaxy A14",
        "versao": "Galaxy A14 V9",
        "so": "Android 13",
        "interface": "One UI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Samsung",
        "modelo": "Galaxy Z Flip5",
        "versao": "Galaxy Z Flip5 V10",
        "so": "Android 13",
        "interface": "One UI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Apple",
        "modelo": "iPhone 15 Pro Max",
        "versao": "iPhone 15 Pro Max V11",
        "so": "iOS 17",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Apple",
        "modelo": "iPhone 15",
        "versao": "iPhone 15 V12",
        "so": "iOS 17",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Apple",
        "modelo": "iPhone 14 Pro",
        "versao": "iPhone 14 Pro V13",
        "so": "iOS 17",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Apple",
        "modelo": "iPhone 13",
        "versao": "iPhone 13 V14",
        "so": "iOS 17",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Apple",
        "modelo": "iPhone SE (2022)",
        "versao": "iPhone SE (2022) V15",
        "so": "iOS 17",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Apple",
        "modelo": "iPhone 14",
        "versao": "iPhone 14 V16",
        "so": "iOS 17",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Apple",
        "modelo": "iPhone 12",
        "versao": "iPhone 12 V17",
        "so": "iOS 17",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Apple",
        "modelo": "iPhone 11",
        "versao": "iPhone 11 V18",
        "so": "iOS 17",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Apple",
        "modelo": "iPhone 14 Plus",
        "versao": "iPhone 14 Plus V19",
        "so": "iOS 17",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Apple",
        "modelo": "iPhone 13 Mini",
        "versao": "iPhone 13 Mini V20",
        "so": "iOS 17",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Tecno Phantom X2",
        "versao": "Tecno Phantom X2 V21",
        "so": "Android 13",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Tecno Camon 20 Pro",
        "versao": "Tecno Camon 20 Pro V22",
        "so": "Android 13",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Tecno Spark 10",
        "versao": "Tecno Spark 10 V23",
        "so": "Android 13",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Tecno Pova 5",
        "versao": "Tecno Pova 5 V24",
        "so": "Android 13",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Tecno Pop 7",
        "versao": "Tecno Pop 7 V25",
        "so": "Android 13",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Tecno Camon 19 Pro",
        "versao": "Tecno Camon 19 Pro V26",
        "so": "Android 13",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Tecno Spark 9",
        "versao": "Tecno Spark 9 V27",
        "so": "Android 13",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Tecno Pova Neo",
        "versao": "Tecno Pova Neo V28",
        "so": "Android 13",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Tecno Phantom V Fold",
        "versao": "Tecno Phantom V Fold V29",
        "so": "Android 13",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Tecno Camon 17",
        "versao": "Tecno Camon 17 V30",
        "so": "Android 13",
        "interface": "Puro",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Xiaomi",
        "modelo": "Xiaomi 13 Pro",
        "versao": "Xiaomi 13 Pro V31",
        "so": "Android 13",
        "interface": "MIUI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Xiaomi",
        "modelo": "Redmi Note 12",
        "versao": "Redmi Note 12 V32",
        "so": "Android 13",
        "interface": "MIUI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Xiaomi",
        "modelo": "Redmi Note 12 Pro",
        "versao": "Redmi Note 12 Pro V33",
        "so": "Android 13",
        "interface": "MIUI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Xiaomi",
        "modelo": "Poco X5 Pro",
        "versao": "Poco X5 Pro V34",
        "so": "Android 13",
        "interface": "MIUI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Xiaomi",
        "modelo": "Xiaomi 12T",
        "versao": "Xiaomi 12T V35",
        "so": "Android 13",
        "interface": "MIUI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Xiaomi",
        "modelo": "Redmi 10C",
        "versao": "Redmi 10C V36",
        "so": "Android 13",
        "interface": "MIUI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Xiaomi",
        "modelo": "Xiaomi Mi 11",
        "versao": "Xiaomi Mi 11 V37",
        "so": "Android 13",
        "interface": "MIUI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Xiaomi",
        "modelo": "Redmi Note 11",
        "versao": "Redmi Note 11 V38",
        "so": "Android 13",
        "interface": "MIUI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Xiaomi",
        "modelo": "Poco F4",
        "versao": "Poco F4 V39",
        "so": "Android 13",
        "interface": "MIUI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Xiaomi",
        "modelo": "Xiaomi 13 Ultra",
        "versao": "Xiaomi 13 Ultra V40",
        "so": "Android 13",
        "interface": "MIUI",
        "processador": "Snapdragon 8 Gen 2",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": False,
        "gpu": "Adreno 740",
        "tela": "AMOLED",
        "tamanho": 6.5,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP",
        "cam_traseira": "50 MP, 12 MP, 8 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e metal",
        "peso": 190.0,
        "resistencia": "IP67",
        "preco": 699.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-01",
        "suporte_caneta": False,
        "dual_sim": True
    }
]
import time
c = [
    {
        "marca": "Tecno",
        "modelo": "Camon 30 Premier 5G",
        "versao": "CL8",
        "so": "Android 14",
        "interface": "HiOS 14",
        "processador": "MediaTek Dimensity 8200 Ultimate",
        "ram": "12 GB",
        "armazenamento": "512 GB",
        "expansivel": "False",
        "gpu": "Mali-G610 MC6",
        "tela": "LTPO AMOLED",
        "tamanho": 6.77,
        "resolucao": "2780x1264",
        "taxa_update": "120Hz",
        "cam_frontal": "50 MP f/2.5",
        "cam_traseira": "50 MP, 50 MP, 50 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "70W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.2",
        "nfc": True,
        "material": "Vidro e alumínio",
        "peso": 210.0,
        "resistencia": "IP54",
        "preco": 499.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2024-04-02",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Pova 6 Pro 5G",
        "versao": "LH8",
        "so": "Android 14",
        "interface": "HiOS 14",
        "processador": "MediaTek Dimensity 6080",
        "ram": "12 GB",
        "armazenamento": "256 GB",
        "expansivel": "True",
        "gpu": "Mali-G57 MC2",
        "tela": "AMOLED",
        "tamanho": 6.78,
        "resolucao": "2460x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "32 MP f/2.5",
        "cam_traseira": "108 MP, 2 MP, AI Lens",
        "video": "2K a 30fps",
        "cap_bateria": "6000 mAh",
        "carregamento": "70W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 5",
        "bluetooth": "5.3",
        "nfc": False,
        "material": "Plástico",
        "peso": 198.0,
        "resistencia": "Não especificado",
        "preco": 299.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2024-03-29",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Spark 20 Pro+",
        "versao": "KI8",
        "so": "Android 14",
        "interface": "HiOS 14",
        "processador": "MediaTek Helio G99 Ultimate",
        "ram": "8 GB",
        "armazenamento": "256 GB",
        "expansivel": "True",
        "gpu": "Mali-G57 MC2",
        "tela": "AMOLED",
        "tamanho": 6.78,
        "resolucao": "2460x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "32 MP f/2.2",
        "cam_traseira": "108 MP, 0.08 MP",
        "video": "2K a 30fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "33W com fio",
        "_5g": False,
        "wifi": "Wi-Fi 5",
        "bluetooth": "5.2",
        "nfc": False,
        "material": "Plástico",
        "peso": 190.0,
        "resistencia": "Não especificado",
        "preco": 199.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-12-29",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Phantom X2 Pro",
        "versao": "AD8",
        "so": "Android 12",
        "interface": "HiOS 12",
        "processador": "MediaTek Dimensity 9000",
        "ram": "12 GB",
        "armazenamento": "256 GB",
        "expansivel": "False",
        "gpu": "Mali-G710 MC10",
        "tela": "AMOLED",
        "tamanho": 6.8,
        "resolucao": "2400x1080",
        "taxa_update": "120Hz",
        "cam_frontal": "32 MP f/2.5",
        "cam_traseira": "50 MP, 50 MP, 13 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5160 mAh",
        "carregamento": "45W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.3",
        "nfc": True,
        "material": "Plástico e vidro",
        "peso": 201.0,
        "resistencia": "Não especificado",
        "preco": 529.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-01-09",
        "suporte_caneta": False,
        "dual_sim": True
    },
    {
        "marca": "Tecno",
        "modelo": "Phantom V Fold",
        "versao": "AD10",
        "so": "Android 13",
        "interface": "HiOS 13 Fold",
        "processador": "MediaTek Dimensity 9000+",
        "ram": "12 GB",
        "armazenamento": "512 GB",
        "expansivel": "False",
        "gpu": "Mali-G710 MC10",
        "tela": "AMOLED dobrável",
        "tamanho": 7.85,
        "resolucao": "2296x2000",
        "taxa_update": "120Hz",
        "cam_frontal": "16 MP + 32 MP",
        "cam_traseira": "50 MP, 50 MP, 13 MP",
        "video": "4K a 60fps",
        "cap_bateria": "5000 mAh",
        "carregamento": "45W com fio",
        "_5g": True,
        "wifi": "Wi-Fi 6",
        "bluetooth": "5.3",
        "nfc": True,
        "material": "Plástico e alumínio",
        "peso": 299.0,
        "resistencia": "Não especificado",
        "preco": 999.99,
        "moeda": "USD",
        "disponivel": True,
        "lancamento": "2023-04-12",
        "suporte_caneta": False,
        "dual_sim": True
    },
      {
          "marca": "Apple",
          "modelo": "iPhone 15 Pro Max",
          "versao": "A2849",
          "so": "iOS 17",
          "interface": "iOS",
          "processador": "Apple A17 Pro",
          "ram": "8 GB",
          "armazenamento": "1 TB",
          "expansivel": "False",
          "gpu": "Apple GPU (6 núcleos)",
          "tela": "Super Retina XDR OLED",
          "tamanho": 6.7,
          "resolucao": "2796x1290",
          "taxa_update": "120Hz",
          "cam_frontal": "12 MP f/1.9",
          "cam_traseira": "48 MP, 12 MP, 12 MP",
          "video": "4K a 60fps",
          "cap_bateria": "4422 mAh",
          "carregamento": "27W com fio, 15W MagSafe",
          "_5g": True,
          "wifi": "Wi-Fi 6E",
          "bluetooth": "5.3",
          "nfc": True,
          "material": "Titânio e vidro",
          "peso": 221.0,
          "resistencia": "IP68",
          "preco": 1599.99,
          "moeda": "USD",
          "disponivel": True,
          "lancamento": "2023-09-22",
          "suporte_caneta": False,
          "dual_sim": True
      },
      {
          "marca": "Apple",
          "modelo": "iPhone 14",
          "versao": "A2882",
          "so": "iOS 17",
          "interface": "iOS",
          "processador": "Apple A15 Bionic",
          "ram": "6 GB",
          "armazenamento": "128 GB",
          "expansivel": "False",
          "gpu": "Apple GPU (5 núcleos)",
          "tela": "Super Retina XDR OLED",
          "tamanho": 6.1,
          "resolucao": "2532x1170",
          "taxa_update": "60Hz",
          "cam_frontal": "12 MP f/1.9",
          "cam_traseira": "12 MP, 12 MP",
          "video": "4K a 60fps",
          "cap_bateria": "3279 mAh",
          "carregamento": "20W com fio, 15W MagSafe",
          "_5g": True,
          "wifi": "Wi-Fi 6",
          "bluetooth": "5.3",
          "nfc": True,
          "material": "Alumínio e vidro",
          "peso": 172.0,
          "resistencia": "IP68",
          "preco": 799.99,
          "moeda": "USD",
          "disponivel": True,
          "lancamento": "2022-09-16",
          "suporte_caneta": False,
          "dual_sim": True
      },
      {
          "marca": "Apple",
          "modelo": "iPhone SE (3ª geração)",
          "versao": "A2783",
          "so": "iOS 17",
          "interface": "iOS",
          "processador": "Apple A15 Bionic",
          "ram": "4 GB",
          "armazenamento": "128 GB",
          "expansivel": "False",
          "gpu": "Apple GPU (4 núcleos)",
          "tela": "Retina IPS LCD",
          "tamanho": 4.7,
          "resolucao": "1334x750",
          "taxa_update": "60Hz",
          "cam_frontal": "7 MP f/2.2",
          "cam_traseira": "12 MP",
          "video": "4K a 60fps",
          "cap_bateria": "2018 mAh",
          "carregamento": "20W com fio",
          "_5g": True,
          "wifi": "Wi-Fi 6",
          "bluetooth": "5.0",
          "nfc": True,
          "material": "Alumínio e vidro",
          "peso": 144.0,
          "resistencia": "IP67",
          "preco": 429.99,
          "moeda": "USD",
          "disponivel": True,
          "lancamento": "2022-03-18",
          "suporte_caneta": False,
          "dual_sim": True
      },
      {
          "marca": "Apple",
          "modelo": "iPhone 15",
          "versao": "A3090",
          "so": "iOS 17",
          "interface": "iOS",
          "processador": "Apple A16 Bionic",
          "ram": "6 GB",
          "armazenamento": "256 GB",
          "expansivel": "False",
          "gpu": "Apple GPU (5 núcleos)",
          "tela": "Super Retina XDR OLED",
          "tamanho": 6.1,
          "resolucao": "2556x1179",
          "taxa_update": "60Hz",
          "cam_frontal": "12 MP f/1.9",
          "cam_traseira": "48 MP, 12 MP",
          "video": "4K a 60fps",
          "cap_bateria": "3349 mAh",
          "carregamento": "20W com fio, 15W MagSafe",
          "_5g": True,
          "wifi": "Wi-Fi 6E",
          "bluetooth": "5.3",
          "nfc": True,
          "material": "Alumínio e vidro",
          "peso": 171.0,
          "resistencia": "IP68",
          "preco": 899.99,
          "moeda": "USD",
          "disponivel": True,
          "lancamento": "2023-09-22",
          "suporte_caneta": False,
          "dual_sim": True
      },
      {
          "marca": "Apple",
          "modelo": "iPhone 15 Plus",
          "versao": "A3094",
          "so": "iOS 17",
          "interface": "iOS",
          "processador": "Apple A16 Bionic",
          "ram": "6 GB",
          "armazenamento": "256 GB",
          "expansivel": "False",
          "gpu": "Apple GPU (5 núcleos)",
          "tela": "Super Retina XDR OLED",
          "tamanho": 6.7,
          "resolucao": "2796x1290",
          "taxa_update": "60Hz",
          "cam_frontal": "12 MP f/1.9",
          "cam_traseira": "48 MP, 12 MP",
          "video": "4K a 60fps",
          "cap_bateria": "4383 mAh",
          "carregamento": "20W com fio, 15W MagSafe",
          "_5g": True,
          "wifi": "Wi-Fi 6E",
          "bluetooth": "5.3",
          "nfc": True,
          "material": "Alumínio e vidro",
          "peso": 201.0,
          "resistencia": "IP68",
          "preco": 999.99,
          "moeda": "USD",
          "disponivel": True,
          "lancamento": "2023-09-22",
          "suporte_caneta": False,
          "dual_sim": True
      },
        {
            "marca": "Samsung",
            "modelo": "Galaxy Z Fold5",
            "versao": "SM-F946B",
            "so": "Android 13",
            "interface": "One UI 5.1.1",
            "processador": "Snapdragon 8 Gen 2",
            "ram": "12 GB",
            "armazenamento": "512 GB",
            "expansivel": "False",
            "gpu": "Adreno 740",
            "tela": "Dynamic AMOLED 2X",
            "tamanho": 7.6,
            "resolucao": "2176x1812",
            "taxa_update": "120Hz",
            "cam_frontal": "4 MP f/1.8 + 10 MP f/2.2",
            "cam_traseira": "50 MP, 12 MP, 10 MP",
            "video": "8K a 30fps",
            "cap_bateria": "4400 mAh",
            "carregamento": "25W com fio, 15W sem fio",
            "_5g": True,
            "wifi": "Wi-Fi 6E",
            "bluetooth": "5.3",
            "nfc": True,
            "material": "Alumínio e vidro",
            "peso": 253.0,
            "resistencia": "IPX8",
            "preco": 1799.99,
            "moeda": "USD",
            "disponivel": True,
            "lancamento": "2023-08-11",
            "suporte_caneta": True,
            "dual_sim": True
        },
        {
            "marca": "Samsung",
            "modelo": "Galaxy A55 5G",
            "versao": "SM-A556B",
            "so": "Android 14",
            "interface": "One UI 6.1",
            "processador": "Exynos 1480",
            "ram": "8 GB",
            "armazenamento": "256 GB",
            "expansivel": "True",
            "gpu": "Xclipse 530",
            "tela": "Super AMOLED",
            "tamanho": 6.6,
            "resolucao": "2340x1080",
            "taxa_update": "120Hz",
            "cam_frontal": "32 MP f/2.2",
            "cam_traseira": "50 MP, 12 MP, 5 MP",
            "video": "4K a 30fps",
            "cap_bateria": "5000 mAh",
            "carregamento": "25W com fio",
            "_5g": True,
            "wifi": "Wi-Fi 6",
            "bluetooth": "5.3",
            "nfc": True,
            "material": "Alumínio e vidro",
            "peso": 213.0,
            "resistencia": "IP67",
            "preco": 449.99,
            "moeda": "USD",
            "disponivel": True,
            "lancamento": "2024-03-15",
            "suporte_caneta": False,
            "dual_sim": True
        },
        {
            "marca": "Samsung",
            "modelo": "Galaxy S23 FE",
            "versao": "SM-S711B",
            "so": "Android 13",
            "interface": "One UI 6",
            "processador": "Exynos 2200",
            "ram": "8 GB",
            "armazenamento": "256 GB",
            "expansivel": "False",
            "gpu": "Xclipse 920",
            "tela": "Dynamic AMOLED 2X",
            "tamanho": 6.4,
            "resolucao": "2340x1080",
            "taxa_update": "120Hz",
            "cam_frontal": "10 MP f/2.4",
            "cam_traseira": "50 MP, 12 MP, 8 MP",
            "video": "8K a 24fps",
            "cap_bateria": "4500 mAh",
            "carregamento": "25W com fio, 15W sem fio",
            "_5g": True,
            "wifi": "Wi-Fi 6E",
            "bluetooth": "5.3",
            "nfc": True,
            "material": "Alumínio e vidro",
            "peso": 209.0,
            "resistencia": "IP68",
            "preco": 599.99,
            "moeda": "USD",
            "disponivel": True,
            "lancamento": "2023-10-05",
            "suporte_caneta": False,
            "dual_sim": True
        },
        {
            "marca": "Samsung",
            "modelo": "Galaxy M55 5G",
            "versao": "SM-M556B",
            "so": "Android 14",
            "interface": "One UI 6.1",
            "processador": "Snapdragon 7 Gen 1",
            "ram": "8 GB",
            "armazenamento": "256 GB",
            "expansivel": "True",
            "gpu": "Adreno 644",
            "tela": "Super AMOLED+",
            "tamanho": 6.7,
            "resolucao": "2400x1080",
            "taxa_update": "120Hz",
            "cam_frontal": "50 MP f/2.4",
            "cam_traseira": "50 MP, 8 MP, 2 MP",
            "video": "4K a 30fps",
            "cap_bateria": "5000 mAh",
            "carregamento": "45W com fio",
            "_5g": True,
            "wifi": "Wi-Fi 6",
            "bluetooth": "5.2",
            "nfc": True,
            "material": "Plástico",
            "peso": 180.0,
            "resistencia": "Não especificado",
            "preco": 399.99,
            "moeda": "USD",
            "disponivel": True,
            "lancamento": "2024-04-28",
            "suporte_caneta": False,
            "dual_sim": True
        },
        {
            "marca": "Samsung",
            "modelo": "Galaxy S24 Ultra",
            "versao": "SM-S928B",
            "so": "Android 14",
            "interface": "One UI 6.1",
            "processador": "Snapdragon 8 Gen 3",
            "ram": "12 GB",
            "armazenamento": "1 TB",
            "expansivel": "False",
            "gpu": "Adreno 750",
            "tela": "Dynamic AMOLED 2X",
            "tamanho": 6.8,
            "resolucao": "3120x1440",
            "taxa_update": "120Hz",
            "cam_frontal": "12 MP f/2.2",
            "cam_traseira": "200 MP, 12 MP, 50 MP, 10 MP",
            "video": "8K a 30fps",
            "cap_bateria": "5000 mAh",
            "carregamento": "45W com fio, 15W sem fio",
            "_5g": True,
            "wifi": "Wi-Fi 7",
            "bluetooth": "5.3",
            "nfc": True,
            "material": "Titânio e vidro",
            "peso": 232.0,
            "resistencia": "IP68",
            "preco": 1399.99,
            "moeda": "USD",
            "disponivel": True,
            "lancamento": "2024-01-31",
            "suporte_caneta": True,
            "dual_sim": True
        }
]
d= [
    {
            "marca": "Samsung",
            "modelo": "Galaxy S24 Ultra",
            "versao": "SM-S928B",
            "so": "Android 14",
            "interface": "One UI 6.1",
            "processador": "Snapdragon 8 Gen 3",
            "ram": "12 GB",
            "armazenamento": "1 TB",
            "expansivel": "False",
            "gpu": "Adreno 750",
            "tela": "Dynamic AMOLED 2X",
            "tamanho": 6.8,
            "resolucao": "3120x1440",
            "taxa_update": "120Hz",
            "cam_frontal": "12 MP f/2.2",
            "cam_traseira": "200 MP, 12 MP, 50 MP, 10 MP",
            "video": "8K a 30fps",
            "cap_bateria": "5000 mAh",
            "carregamento": "45W com fio, 15W sem fio",
            "_5g": True,
            "wifi": "Wi-Fi 7",
            "bluetooth": "5.3",
            "nfc": True,
            "material": "Titânio e vidro",
            "peso": 232.0,
            "resistencia": "IP68",
            "preco": 1399.99,
            "moeda": "USD",
            "disponivel": True,
            "lancamento": "2024-01-31",
            "suporte_caneta": True,
            "dual_sim": True
        }
]
def add_celular(celular):
    try:
        res = requests.post(url, json=celular)
        if res.status_code == 201:
            print("Sucesso:", res.json())
        else:
            print("Erro ao adicionar celular:", res.status_code, res.text)
    except Exception as e :
        print(e)
n= 0
for c in c:
    add_celular(c)